# https://www.appveyor.com/docs/lang/nodejs-iojs/
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # NPM v3 has flaky permission issues on Windows
  - npm install -g npm@5
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node -e "console.log(process.platform)"
  - node -e "console.log(process.arch)"
  # wait-on, npm-run-all and other useful utilities
  - npm install
  # for now install global utils
  - npm install -g wait-on npm-run-all ok-file commit-message-install@1.3.3

# Post-install test scripts.
test_script:
  - npm run test-if -- cypress-example-todomvc
  - npm run test-if -- cypress-example-kitchensink
  - npm run test-if -- cypress-example-recipes
  - npm run test-if -- cypress-example-phonecat
  - npm run test-if -- cypress-example-piechopper

# Don't actually build.
build: off
