# https://www.appveyor.com/docs/lang/nodejs-iojs/
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # NPM v3 has flaky permission issues on Windows
  - npm install -g npm@5
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node -e "console.log(process.platform)"
  - node -e "console.log(process.arch)"
  - echo Will be installing %CYPRESS_NPM_PACKAGE_NAME%
  - echo and binary version %CYPRESS_BINARY_VERSION%

# Post-install test scripts.
test_script:
  - git clone https://github.com/cypress-io/cypress-example-kitchensink.git
  - cd cypress-example-kitchensink
  # only install the server package
  - npm install --production
  - npm install %CYPRESS_NPM_PACKAGE_NAME%

# Don't actually build.
build: off
