version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome62
      environment:
        ## this enables colors + fixes failing unit tests
        TERM: xterm
        # avoid million NPM install messages
        npm_config_loglevel: warn
        COMMIT_MESSAGE_INSTALL: commit-message-install@1.3.3

jobs:
  "example-group-staging":
    <<: *defaults
    steps:
      - checkout
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps-group
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-group
          command: rm -rf .git
      - run:
          working_directory: cypress-example-group
          command: npm install
      - run:
          working_directory: cypress-example-group
          command: npm install $COMMIT_MESSAGE_INSTALL
      - save_cache:
          key: deps-group-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run:
          working_directory: cypress-example-group
          command: $(npm bin)/commit-message-install
      - run:
          name: Run a test that is part of a group
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/run-if npm run cy:run -- --group --record --group-id $CIRCLE_BUILD_NUM
      - run:
          name: Run test using Chrome but put in the same group
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/run-if npm run cy:run -- --group --record --browser chrome --group-id $CIRCLE_BUILD_NUM

  # pass explicit group id to run same tests multiple times
  # using CircleCI parallelism option
  # https://circleci.com/docs/2.0/configuration-reference/#job_name
  # all jobs will have same CIRCLE_BUILD_NUM for example
  "example-group-id-staging":
    <<: *defaults
    parallelism: 4
    steps:
      - checkout
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps-group
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-group
          command: rm -rf .git
      - run:
          working_directory: cypress-example-group
          command: npm install
      - run:
          working_directory: cypress-example-group
          command: npm install $COMMIT_MESSAGE_INSTALL
      - save_cache:
          key: deps-group-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run:
          working_directory: cypress-example-group
          command: $(npm bin)/commit-message-install
      - run:
          name: Run tests and group them by build number
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/run-if npm run cy:run -- --group --record --group-id $CIRCLE_BUILD_NUM

  kitchensink:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-kitchensink

  "kitchensink-chrome":
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-kitchensink test:ci:chrome

  recipes:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-recipes

  recipes-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-recipes test:ci:chrome

  todomvc:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-todomvc test:ci

  todomvc-headed:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-todomvc test:ci:headed

  todomvc-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-todomvc test:ci:chrome

  phonecat:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- cypress-example-phonecat test:ci

  piechopper:
    <<: *defaults
    steps:
      - checkout
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-piechopper.git
      - restore_cache:
          key: deps-piechopper
      - run:
          working_directory: cypress-example-piechopper
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-piechopper
          command: rm -rf .git
      - run:
          name: Install wait-on
          working_directory: cypress-example-piechopper
          command: npm install wait-on
      - run:
          name: install dependencies
          working_directory: cypress-example-piechopper
          command: npm install
      - run:
          working_directory: cypress-example-piechopper
          command: npm install $COMMIT_MESSAGE_INSTALL
      - save_cache:
          key: deps-piechopper-{{ checksum "cypress-example-piechopper/package.json" }}
          paths:
            - cypress-example-piechopper/node_modules
      - run:
          working_directory: cypress-example-piechopper
          command: $(npm bin)/commit-message-install
      - run:
          working_directory: cypress-example-piechopper
          command: npm run build
      - run:
          working_directory: cypress-example-piechopper
          command: npm start
          background: true
      - run:
          name: Wait for server
          working_directory: cypress-example-piechopper
          command: $(npm bin)/wait-on http://localhost:8080
      - run:
          working_directory: cypress-example-piechopper
          command: $(npm bin)/run-if npm run cypress:run

workflows:
  version: 2
  test-example-repos:
    jobs:
      - kitchensink
      - kitchensink-chrome
      - example-group-staging
      - example-group-id-staging
      - recipes
      - recipes-chrome
      - todomvc
      - todomvc-headed
      - todomvc-chrome
      - phonecat
      - piechopper
