version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/base:8

jobs:
  kitchensink:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - run: cd cypress-example-kitchensink && npm install
      - run: cd cypress-example-kitchensink && npm install cypress@dev
      - run:
          name: start server
          command: cd cypress-example-kitchensink && npm start
          background: true
      - run: cd cypress-example-kitchensink && $(npm bin)/cypress run

  recipes:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-recipes.git
      - run: |
          cd cypress-example-recipes
          npm install
          npm install cypress@dev
          npm start &
          $(npm bin)/cypress run

  todomvc:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-todomvc.git
      - run: |
          cd cypress-example-todomvc
          npm install
          npm install cypress@dev
          npm start &
          $(npm bin)/cypress run

  phonecat:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-phonecat.git
      - run: |
          cd cypress-example-phonecat
          npm install
          npm install wait-on
          npm install cypress@dev
          npm start &
          $(npm bin)/wait-on http://localhost:8000 && $(npm bin)/cypress run

  piechopper:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-piechopper.git
      - run: |
          cd cypress-example-piechopper
          npm install
          npm install wait-on
          npm install cypress@dev
          npm run build
          npm start &
          $(npm bin)/wait-on http://localhost:8080 && $(npm bin)/cypress run

workflows:
  version: 2
  test-example-repos:
    jobs:
      - kitchensink
      - recipes
      - todomvc
      - phonecat
      - piechopper
