version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome64
      environment:
        COMMIT_MESSAGE_INSTALL: commit-message-install@1.10.1

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-group
      - run: npm install
      - save_cache:
          key: root-group-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint

  "example-group-staging":
    <<: *defaults
    steps:
      - checkout
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps-example-group-staging
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-group
          command: rm -rf .git
      - run:
          working_directory: cypress-example-group
          command: npm install
      - run:
          working_directory: cypress-example-group
          command: npm install $COMMIT_MESSAGE_INSTALL
      - save_cache:
          key: deps-example-group-staging-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run:
          working_directory: cypress-example-group
          command: $(npm bin)/commit-message-install
      - run:
          name: Run a test that is part of a group
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/run-if npm run cy:run -- --group --record --group-id $CIRCLE_BUILD_NUM
      - run:
          name: Run test using Chrome but put in the same group
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/run-if npm run cy:run -- --group --record --browser chrome --group-id $CIRCLE_BUILD_NUM

  # pass explicit group id to run same tests multiple times
  # using CircleCI parallelism option
  # https://circleci.com/docs/2.0/configuration-reference/#job_name
  # all jobs will have same CIRCLE_BUILD_NUM for example
  "example-group-id-staging":
    <<: *defaults
    parallelism: 4
    steps:
      - checkout
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps-example-group-id-staging
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-group
          command: rm -rf .git
      - run:
          working_directory: cypress-example-group
          command: npm install
      - run:
          working_directory: cypress-example-group
          command: npm install $COMMIT_MESSAGE_INSTALL
      - save_cache:
          key: deps-example-group-id-staging-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run:
          working_directory: cypress-example-group
          command: $(npm bin)/commit-message-install
      - run:
          name: Run tests and group them by build number
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/run-if npm run cy:run -- --group --record --group-id $CIRCLE_BUILD_NUM

  kitchensink:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-kitchensink
      - store_artifacts:
          path: cypress-example-kitchensink/cypress/screenshots
      - store_artifacts:
          path: cypress-example-kitchensink/cypress/videos

  "kitchensink-chrome":
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-kitchensink --command test:ci:chrome
      - store_artifacts:
          path: cypress-example-kitchensink/cypress/screenshots
      - store_artifacts:
          path: cypress-example-kitchensink/cypress/videos

  recipes:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-recipes --command test:ci:record

  recipes-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-recipes --command test:ci:chrome:record

  todomvc:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-todomvc --command test:ci:record

  todomvc-headed:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-todomvc --command test:ci:headed

  todomvc-chrome:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-todomvc --command test:ci:chrome

  phonecat:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-phonecat --command test:ci

  piechopper:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo cypress-example-piechopper --command test:ci

  cypress-svelte-unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo bahmutov/cypress-svelte-unit-test --command test

  cypress-vue-unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo bahmutov/cypress-vue-unit-test --command test

  cypress-react-unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      # temporary fix until https://github.com/bahmutov/cypress-react-unit-test/pull/67 is merged
      - run: npm run test-if -- --repo bahmutov/cypress-react-unit-test --command transpile
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo bahmutov/cypress-react-unit-test --command test

  cypress-hyperapp-unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo bahmutov/cypress-hyperapp-unit-test --command test:ci

  cypress-cycle-unit-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: root-deps
      - run: npm install
      - save_cache:
          key: root-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test-if -- --repo bahmutov/cypress-cycle-unit-test --command test

workflows:
  version: 2
  test-example-repos:
    jobs:
      - lint
      - kitchensink
      - kitchensink-chrome
      # - example-group-staging
      # - example-group-id-staging
      - recipes
      - recipes-chrome
      - todomvc
      - todomvc-headed
      - todomvc-chrome
      - phonecat
      - piechopper
      - cypress-svelte-unit-test
      - cypress-vue-unit-test
      - cypress-react-unit-test
      - cypress-hyperapp-unit-test
      - cypress-cycle-unit-test
