version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome62
      environment:
        ## this enables colors + fixes failing unit tests
        TERM: xterm
        # avoid million NPM install messages
        npm_config_loglevel: warn

jobs:
  "example-group-staging":
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-group
          command: rm -rf .git
      - run:
          working_directory: cypress-example-group
          command: npm install
      - save_cache:
          key: deps-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-group
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: Run a test that is part of a group
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/cypress run --group --record --group-id $CIRCLE_BUILD_NUM
      - run:
          name: Run test using Chrome but put in the same group
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/cypress run --group --record --browser chrome --group-id $CIRCLE_BUILD_NUM

  # pass explicit group id to run same tests multiple times
  # using CircleCI parallelism option
  # https://circleci.com/docs/2.0/configuration-reference/#job_name
  # all jobs will have same CIRCLE_BUILD_NUM for example
  "example-group-id-staging":
    <<: *defaults
    parallelism: 4
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-group
          command: rm -rf .git
      - run:
          working_directory: cypress-example-group
          command: npm install
      - save_cache:
          key: deps-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-group
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: Run tests and group them by build number
          working_directory: cypress-example-group
          command: |
            CYPRESS_ENV=staging \
            CYPRESS_PROJECT_ID=$EXAMPLE_GROUP_STAGING_PROJECT_ID \
            CYPRESS_RECORD_KEY=$EXAMPLE_GROUP_STAGING_RECORD_KEY \
            $(npm bin)/cypress run --group --record --group-id $CIRCLE_BUILD_NUM

  kitchensink:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - restore_cache:
          key: deps
      - run:
          working_directory: cypress-example-kitchensink
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-kitchensink
          command: rm -rf .git
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install commit-message-install@1.3.1
      - save_cache:
          key: deps-{{ checksum "cypress-example-kitchensink/package.json" }}
          paths:
            - cypress-example-kitchensink/node_modules
      - run:
          working_directory: cypress-example-kitchensink
          command: $(npm bin)/commit-message-install
      - run:
          working_directory: cypress-example-kitchensink
          command: $(npm bin)/run-if npm run test-ci

  "kitchensink-chrome":
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-kitchensink.git
      - restore_cache:
          key: deps-kitchensink
      - run:
          working_directory: cypress-example-kitchensink
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-kitchensink
          command: rm -rf .git
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install commit-message-install@1.3.1
      - save_cache:
          key: deps-kitchensink-{{ checksum "cypress-example-kitchensink/package.json" }}
          paths:
            - cypress-example-kitchensink/node_modules
      - run:
          working_directory: cypress-example-kitchensink
          command: $(npm bin)/commit-message-install
      - run:
          working_directory: cypress-example-kitchensink
          command: $(npm bin)/run-if npm run test-ci-chrome

  recipes:
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-recipes.git
      - restore_cache:
          key: deps-recipes
      - run:
          working_directory: cypress-example-recipes
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-recipes
          command: rm -rf .git
      - run:
          working_directory: cypress-example-recipes
          command: npm install
      - run:
          working_directory: cypress-example-recipes
          command: npm install commit-message-install@1.3.1
      - save_cache:
          key: deps-recipes-{{ checksum "cypress-example-recipes/package.json" }}
          paths:
            - cypress-example-recipes/node_modules
      - run:
          working_directory: cypress-example-recipes
          command: $(npm bin)/commit-message-install
      - run:
          working_directory: cypress-example-recipes
          command: $(npm bin)/run-if npm run test:ci

  "recipes-chrome":
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-recipes.git
      - restore_cache:
          key: deps-recipes
      - run:
          working_directory: cypress-example-recipes
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-recipes
          command: rm -rf .git
      - run:
          working_directory: cypress-example-recipes
          command: npm install
      - run:
          working_directory: cypress-example-recipes
          command: npm install commit-message-install@1.3.1
      - save_cache:
          key: deps-recipes-{{ checksum "cypress-example-recipes/package.json" }}
          paths:
            - cypress-example-recipes/node_modules
      - run:
          working_directory: cypress-example-recipes
          command: $(npm bin)/commit-message-install
      - run:
          working_directory: cypress-example-recipes
          command: $(npm bin)/run-if npm run test:ci:chrome

  todomvc:
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-todomvc.git
      - run:
          working_directory: cypress-example-todomvc
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-todomvc
          command: rm -rf .git
      - run:
          working_directory: cypress-example-todomvc
          command: |
            CYPRESS_BINARY_VERSION= npm install
            echo install $CYPRESS_NPM_PACKAGE_NAME
            npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-todomvc
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-todomvc
          command: $(npm bin)/cypress run --headed

  "todomvc-chrome":
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-todomvc.git
      - run:
          working_directory: cypress-example-todomvc
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-todomvc
          command: rm -rf .git
      - run:
          working_directory: cypress-example-todomvc
          command: |
            CYPRESS_BINARY_VERSION= npm install
            echo install $CYPRESS_NPM_PACKAGE_NAME
            npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-todomvc
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-todomvc
          command: $(npm bin)/cypress run --browser chrome

  phonecat:
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-phonecat.git
      - run:
          working_directory: cypress-example-phonecat
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-phonecat
          command: rm -rf .git
      - run:
          name: Install default dependencies
          working_directory: cypress-example-phonecat
          command: CYPRESS_BINARY_VERSION= npm install || true
      - run:
          name: Install wait-on
          working_directory: cypress-example-phonecat
          command: npm install wait-on
      - run: |
          echo install $CYPRESS_NPM_PACKAGE_NAME
          echo and binary $CYPRESS_BINARY_VERSION
      - run:
          name: Install new version of Cypress
          working_directory: cypress-example-phonecat
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: Starting server
          background: true
          working_directory: cypress-example-phonecat
          command: npm start
      - run:
          name: Wait for server
          working_directory: cypress-example-phonecat
          command: $(npm bin)/wait-on http://localhost:8000
      - run:
          name: Run E2E tests
          working_directory: cypress-example-phonecat
          command: $(npm bin)/cypress run --browser chrome

  piechopper:
    <<: *defaults
    steps:
      - run: git clone --depth 1 https://github.com/cypress-io/cypress-example-piechopper.git
      - run:
          working_directory: cypress-example-piechopper
          command: git log -1
      - run:
          name: Remove .git subfolder
          working_directory: cypress-example-piechopper
          command: rm -rf .git
      - run:
          name: Install wait-on
          working_directory: cypress-example-piechopper
          command: npm install wait-on
      - run:
          name: install dependencies
          working_directory: cypress-example-piechopper
          command: CYPRESS_BINARY_VERSION= npm install
      - run:
          name: uninstall listed cypress
          working_directory: cypress-example-piechopper
          command: npm uninstall cypress
      - run:
          name: install specific cypress
          working_directory: cypress-example-piechopper
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-piechopper
          command: npm run build
      - run:
          working_directory: cypress-example-piechopper
          command: npm start
          background: true
      - run:
          name: Wait for server
          working_directory: cypress-example-piechopper
          command: $(npm bin)/wait-on http://localhost:8080
      - run:
          working_directory: cypress-example-piechopper
          command: $(npm bin)/cypress run

workflows:
  version: 2
  test-example-repos:
    jobs:
      - example-group-staging
      - example-group-id-staging
      - kitchensink
      - kitchensink-chrome
      - recipes
      - recipes-chrome
      - todomvc
      - todomvc-chrome
      - phonecat
      - piechopper
