version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome62
      environment:
        ## this enables colors + fixes failing unit tests
        TERM: xterm
        # avoid million NPM install messages
        npm_config_loglevel: warn

jobs:
  "example-group-staging":
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-group.git
      - restore_cache:
          key: deps
      - run:
          working_directory: cypress-example-group
          command: git log -1
      - run:
          working_directory: cypress-example-group
          command: npm install
      - save_cache:
          key: deps-{{ checksum "cypress-example-group/package.json" }}
          paths:
            - cypress-example-group/node_modules
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-group
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: Run a test that is part of a group
          working_directory: cypress-example-group
          command: CYPRESS_ENV=staging $(npm bin)/cypress run --group
      - run:
          name: Run test using Chrome but put in the same group
          working_directory: cypress-example-group
          command: CYPRESS_ENV=staging $(npm bin)/cypress run --browser chrome --group

  kitchensink:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - restore_cache:
          key: deps
      - run:
          working_directory: cypress-example-kitchensink
          command: git log -1
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install
      - save_cache:
          key: deps-{{ checksum "cypress-example-kitchensink/package.json" }}
          paths:
            - cypress-example-kitchensink/node_modules
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: start server
          working_directory: cypress-example-kitchensink
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-kitchensink
          command: $(npm bin)/cypress run

  "kitchensink-chrome":
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - restore_cache:
          key: deps
      - run:
          working_directory: cypress-example-kitchensink
          command: git log -1
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install
      - save_cache:
          key: deps-{{ checksum "cypress-example-kitchensink/package.json" }}
          paths:
            - cypress-example-kitchensink/node_modules
      - run: echo install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-kitchensink
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: start server
          working_directory: cypress-example-kitchensink
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-kitchensink
          command: $(npm bin)/cypress run --browser chrome

  recipes:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-recipes.git
      - run:
          working_directory: cypress-example-recipes
          command: git log -1
      - run:
          working_directory: cypress-example-recipes
          command: |
            CYPRESS_BINARY_VERSION= npm install
            echo install $CYPRESS_NPM_PACKAGE_NAME
            npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-recipes
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-recipes
          command: $(npm bin)/cypress run

  "recipes-chrome":
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-recipes.git
      - run:
          working_directory: cypress-example-recipes
          command: git log -1
      - run:
          working_directory: cypress-example-recipes
          command: |
            CYPRESS_BINARY_VERSION= npm install
            echo install $CYPRESS_NPM_PACKAGE_NAME
            npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-recipes
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-recipes
          command: $(npm bin)/cypress run --browser chrome

  todomvc:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-todomvc.git
      - run:
          working_directory: cypress-example-todomvc
          command: git log -1
      - run:
          working_directory: cypress-example-todomvc
          command: |
            CYPRESS_BINARY_VERSION= npm install
            echo install $CYPRESS_NPM_PACKAGE_NAME
            npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-todomvc
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-todomvc
          command: $(npm bin)/cypress run --headed

  "todomvc-chrome":
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-todomvc.git
      - run:
          working_directory: cypress-example-todomvc
          command: git log -1
      - run:
          working_directory: cypress-example-todomvc
          command: |
            CYPRESS_BINARY_VERSION= npm install
            echo install $CYPRESS_NPM_PACKAGE_NAME
            npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-todomvc
          command: npm start
          background: true
      - run:
          working_directory: cypress-example-todomvc
          command: $(npm bin)/cypress run --browser chrome

  phonecat:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-phonecat.git
      - run:
          working_directory: cypress-example-phonecat
          command: git log -1
      - run:
          name: Install default dependencies
          working_directory: cypress-example-phonecat
          command: CYPRESS_BINARY_VERSION= npm install || true
      - run:
          name: Install wait-on
          working_directory: cypress-example-phonecat
          command: npm install wait-on
      - run: |
          echo install $CYPRESS_NPM_PACKAGE_NAME
          echo and binary $CYPRESS_BINARY_VERSION
      - run:
          name: Install new version of Cypress
          working_directory: cypress-example-phonecat
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          name: Starting server
          background: true
          working_directory: cypress-example-phonecat
          command: npm start
      - run:
          name: Wait for server
          working_directory: cypress-example-phonecat
          command: $(npm bin)/wait-on http://localhost:8000
      - run:
          name: Run E2E tests
          working_directory: cypress-example-phonecat
          command: $(npm bin)/cypress run --browser chrome

  piechopper:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-piechopper.git
      - run:
          working_directory: cypress-example-piechopper
          command: git log -1
      - run:
          name: Install wait-on
          working_directory: cypress-example-piechopper
          command: npm install wait-on
      - run:
          name: install dependencies
          working_directory: cypress-example-piechopper
          command: CYPRESS_BINARY_VERSION= npm install
      - run:
          name: uninstall listed cypress
          working_directory: cypress-example-piechopper
          command: npm uninstall cypress
      - run:
          name: install specific cypress
          working_directory: cypress-example-piechopper
          command: npm install $CYPRESS_NPM_PACKAGE_NAME
      - run:
          working_directory: cypress-example-piechopper
          command: npm run build
      - run:
          working_directory: cypress-example-piechopper
          command: npm start
          background: true
      - run:
          name: Wait for server
          working_directory: cypress-example-piechopper
          command: $(npm bin)/wait-on http://localhost:8080
      - run:
          working_directory: cypress-example-piechopper
          command: $(npm bin)/cypress run

workflows:
  version: 2
  test-example-repos:
    jobs:
      - example-group-staging
      - kitchensink
      - kitchensink-chrome
      - recipes
      - recipes-chrome
      - todomvc
      - todomvc-chrome
      - phonecat
      - piechopper
