version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/base:8

jobs:
  kitchensink:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-kitchensink.git
      - run: |
          cd cypress-example-kitchensink
          npm install
          npm install cypress@dev
          npm start &
          $(npm bin)/cypress run

  recipes:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-recipes.git
      - run: |
          cd cypress-example-recipes
          npm install
          npm install cypress@dev
          npm start &
          $(npm bin)/cypress run

  todomvc:
    <<: *defaults
    steps:
      - run: git clone https://github.com/cypress-io/cypress-example-todomvc.git
      - run: |
          cd cypress-example-todomvc
          npm install
          npm install cypress@dev
          npm start &
          $(npm bin)/cypress run

workflows:
  version: 2
  test-example-repos:
    jobs:
      - kitchensink
      - recipes
      - todomvc
