env:
  TERM: "xterm"

# https://buildkite.com/docs/pipelines/command-step
steps:
  - label: "print environment"
    command:
      - "npm install"
      - "$(npm bin)/print-arch"
      - "$(npm bin)/print-env BUILDKITE"
    timeout_in_minutes: 10

  - "wait"

  - label: "print files"
    command:
      - "echo $PWD"
      - "ls -l"
  - "wait"

  - label: "cypress-example-kitchensink"
    command:
      - "npm run test-if -- --repo cypress-example-kitchensink"
    timeout_in_minutes: 10
  - "wait"

  - label: "cypress-example-recipes"
    command:
      - "npm run test-if -- --repo cypress-example-recipes"
    timeout_in_minutes: 30
  - "wait"

  - label: "cypress-example-todomvc"
    command: "npm run test-if -- --repo cypress-example-todomvc"
    timeout_in_minutes: 30
  - "wait"

  - label: "cypress-example-phonecat"
    command:
      - "npm run test-if -- --repo cypress-example-phonecat"
    timeout_in_minutes: 10
  - "wait"

  - label: "cypress-example-piechopper"
    command:
      - "npm run test-if -- --repo cypress-example-piechopper"
    timeout_in_minutes: 10
  - "wait"
