env:
  TERM: "xterm"

# https://buildkite.com/docs/pipelines/command-step
steps:
  - label: "print environment"
    command:
      - "npm install -g print-arch @bahmutov/print-env"
      - "print-arch"
      - "print-env BUILDKITE"

  - "wait"

  - label: "print files"
    command:
      - "echo $PWD"
      - "ls -l"

  - "wait"

  - label: "cypress-example-kitchensink"
    command:
      - "rm -rf cypress-example-kitchensink || true"
      - "git clone https://github.com/cypress-io/cypress-example-kitchensink.git"
      - "cd cypress-example-kitchensink"
      - "git log -1"
      - "npm install"
      - "npm install $CYPRESS_NPM_PACKAGE_NAME"
      - "npm run test-ci"

  - "wait"

  - label: "cypress-example-recipes"
    command:
      - "echo $PWD"
      - "rm -rf cypress-example-recipes || true"
      - "git clone https://github.com/cypress-io/cypress-example-recipes.git"
      - "cd cypress-example-recipes"
      - "git log -1"
      - "npm install"
      - "npm install $CYPRESS_NPM_PACKAGE_NAME"
      - "npm run test:ci"

  - "wait"

  - label: "cypress-example-todomvc"
    command:
      - "rm -rf cypress-example-todomvc || true"
      - "git clone https://github.com/cypress-io/cypress-example-todomvc.git"
      - "cd cypress-example-todomvc"
      - "git log -1"
      - "npm install"
      - "npm install $CYPRESS_NPM_PACKAGE_NAME"
      - "npm run test:ci"

  - "wait"
