env:
  TERM: "xterm"

# https://buildkite.com/docs/pipelines/command-step
steps:
  - label: "print environment"
    command:
      - "npm install -g print-arch @bahmutov/print-env"
      - "print-arch"
      - "print-env BUILDKITE"

  - "wait"

  - label: "print files"
    command:
      - "echo $PWD"
      - "ls -l"

  - "wait"

  - label: "test kitchensink"
    command:
      - "echo $PWD"
      - "ls cypress-example-kitchensink || git clone https://github.com/cypress-io/cypress-example-kitchensink.git"
      - "cd cypress-example-kitchensink"
      - "echo $PWD"
      - "git pull"
      - "git log -1"
      - "echo finally $PWD"
      - "ls -la"
      - "npm install"
      - "npm install $CYPRESS_NPM_PACKAGE_NAME"
      - "npm run test-ci"

  - "wait"

  - label: "test recipes"
    command:
      - "echo $PWD"
      # - "ls cypress-example-recipes || git clone https://github.com/cypress-io/cypress-example-recipes.git"
      # - "cd cypress-example-recipes"
      # - "git pull"
      # - "git log -1"
      # - "npm install"
      # - "npm install $CYPRESS_NPM_PACKAGE_NAME"
      # - "npm run test:ci"

  - "wait"
