env:
  TERM: "xterm"

# https://buildkite.com/docs/pipelines/command-step
steps:
  - label: "print environment"
    command:
      - "npm install"
      - "$(npm bin)/print-arch"
      - "$(npm bin)/print-env BUILDKITE"

  - "wait"

  - label: "print files"
    command:
      - "echo $PWD"
      - "ls -l"
  - "wait"

  - label: "cypress-example-kitchensink"
    command:
      - "npm run test-if -- cypress-example-kitchensink"
  - "wait"

  - label: "cypress-example-recipes"
    command:
      - "npm run test-if -- cypress-example-recipes"
  - "wait"

  - label: "cypress-example-todomvc"
    command:
      - "npm run test-if -- cypress-example-todomvc"
  - "wait"

  - label: "cypress-example-phonecat"
    command:
      - "npm run test-if -- cypress-example-phonecat"
  - "wait"

  - label: "cypress-example-piechopper"
    command:
      - "npm run test-if -- cypress-example-piechopper"
  - "wait"
